export const INITIAL_PRODUCTS = [
  {
    id: "prod-1",
    name: 'Plancha de Gypsum Standard 1/2"',
    slug: "plancha-gypsum-standard-1-2",
    category: "Gypsum y Placas",
    brand: "Knauf",
    price: 12.5,
    comparePrice: 14.0,
    stock: 140,
    images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?w=200&h=200&fit=crop"],
    isNew: false,
    isFeatured: true,
    isActive: true,
    description: "Plancha de yeso cartón para interiores de alta resistencia.",
    createdAt: "2026-02-15",
  },
  {
    id: "prod-2",
    name: "Perfil Omega Galvanizado 0.45mm",
    slug: "perfil-omega-galvanizado-0-45",
    category: "Perfiles de Acero",
    brand: "Novacero",
    price: 3.25,
    comparePrice: null,
    stock: 85,
    images: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop"],
    isNew: true,
    isFeatured: true,
    isActive: true,
    description: "Perfil metálico galvanizado para armado de estructura de cielo raso.",
    createdAt: "2026-02-18",
  },
  {
    id: "prod-3",
    name: "Panel Acústico Ranurado WPC Roble",
    slug: "panel-acustico-ranurado-wpc-roble",
    category: "Revestimientos WPC",
    brand: "DecoPanel",
    price: 28.9,
    comparePrice: 34.5,
    stock: 22,
    images: ["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=200&h=200&fit=crop"],
    isNew: true,
    isFeatured: true,
    isActive: true,
    description: "Panel de listones de madera sintética para decoración y absorción acústica.",
    createdAt: "2026-02-20",
  },
  {
    id: "prod-4",
    name: "Lámina Mármol PVC UV 2.44x1.22m",
    slug: "lamina-marmol-pvc-uv",
    category: "Mármol PVC",
    brand: "DecoPanel",
    price: 45.0,
    comparePrice: 52.0,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&h=200&fit=crop"],
    isNew: false,
    isFeatured: true,
    isActive: true,
    description: "Lámina decorativa imitación mármol con protección UV para paredes.",
    createdAt: "2026-02-22",
  },
  {
    id: "prod-5",
    name: "Tornillos Drywall 6x1 Punta Fina (Caja 1000u)",
    slug: "tornillos-drywall-6x1-punta-fina",
    category: "Fijaciones y Tornillos",
    brand: "Gyplac",
    price: 6.8,
    comparePrice: null,
    stock: 4,
    images: ["https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=200&h=200&fit=crop"],
    isNew: false,
    isFeatured: false,
    isActive: true,
    description: "Tornillo autorroscante para fijación de planchas de yeso a estructura metálica.",
    createdAt: "2026-02-24",
  },
];

export const INITIAL_CATEGORIES = [
  { id: "cat-1", name: "Gypsum y Placas", slug: "gypsum-y-placas", icon: "Package", productCount: 8 },
  { id: "cat-2", name: "Perfiles de Acero", slug: "perfiles-de-acero", icon: "Building2", productCount: 6 },
  { id: "cat-3", name: "Revestimientos WPC", slug: "revestimientos-wpc", icon: "FolderTree", productCount: 4 },
  { id: "cat-4", name: "Mármol PVC", slug: "marmol-pvc", icon: "FolderTree", productCount: 3 },
  { id: "cat-5", name: "Fijaciones y Tornillos", slug: "fijaciones-y-tornillos", icon: "Tag", productCount: 5 },
];

export const INITIAL_BRANDS = [
  { id: "brand-1", name: "Knauf", slug: "knauf", logo: "K", productCount: 8 },
  { id: "brand-2", name: "Novacero", slug: "novacero", logo: "N", productCount: 6 },
  { id: "brand-3", name: "DecoPanel", slug: "decopanel", logo: "D", productCount: 7 },
  { id: "brand-4", name: "Gyplac", slug: "gyplac", logo: "G", productCount: 5 },
];

export const INITIAL_ORDERS = [
  {
    id: "ord-1",
    orderNumber: "ORD-2026-001",
    customer: {
      name: "Carlos Mendoza",
      email: "carlos.mendoza@gmail.com",
      phone: "+593 98 443 2190",
    },
    status: "processing",
    subtotal: 185.5,
    shipping: 12.0,
    total: 197.5,
    paymentMethod: "TRANSFER",
    shippingAddress: {
      name: "Carlos Mendoza",
      address: "Av. 12 de Octubre y Cordero",
      city: "Quito",
      state: "Pichincha",
      zipCode: "170143",
    },
    items: [
      {
        name: 'Plancha de Gypsum Standard 1/2"',
        quantity: 10,
        price: 12.5,
        total: 125.0,
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=200&h=200&fit=crop",
      },
      {
        name: "Tornillos Drywall 6x1 Punta Fina (Caja 1000u)",
        quantity: 2,
        price: 6.8,
        total: 13.6,
        image: "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=200&h=200&fit=crop",
      },
      {
        name: "Lámina Mármol PVC UV 2.44x1.22m",
        quantity: 1,
        price: 45.0,
        total: 45.0,
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&h=200&fit=crop",
      },
    ],
    createdAt: "2026-02-28 10:45",
  },
  {
    id: "ord-2",
    orderNumber: "ORD-2026-002",
    customer: {
      name: "Ana Belén Paredes",
      email: "ana.paredes@constructora.ec",
      phone: "+593 99 711 9881",
    },
    status: "delivered",
    subtotal: 345.0,
    shipping: 15.0,
    total: 360.0,
    paymentMethod: "CARD",
    shippingAddress: {
      name: "Ana Belén Paredes",
      address: "Urbanización Los Ceibos Mz 14",
      city: "Guayaquil",
      state: "Guayas",
      zipCode: "090150",
    },
    items: [
      {
        name: "Panel Acústico Ranurado WPC Roble",
        quantity: 10,
        price: 28.9,
        total: 289.0,
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=200&h=200&fit=crop",
      },
    ],
    createdAt: "2026-02-27 15:20",
  },
  {
    id: "ord-3",
    orderNumber: "ORD-2026-003",
    customer: {
      name: "Estudio Arquitectura Vértice",
      email: "proyectos@vertice.ec",
      phone: "+593 95 123 4567",
    },
    status: "pending",
    subtotal: 98.0,
    shipping: 8.0,
    total: 106.0,
    paymentMethod: "CARD",
    shippingAddress: {
      name: "Arq. Marcelo Dávila",
      address: "Calle Larga y Huayna Cápac",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010101",
    },
    items: [
      {
        name: "Perfil Omega Galvanizado 0.45mm",
        quantity: 20,
        price: 3.25,
        total: 65.0,
        image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop",
      },
    ],
    createdAt: "2026-02-28 11:30",
  },
];

export const INITIAL_PAYMENTS = [
  {
    id: "PAY-9812",
    orderId: "ORD-2026-001",
    userName: "Carlos Mendoza",
    userEmail: "carlos.mendoza@gmail.com",
    amount: 197.5,
    method: "transfer",
    status: "completed",
    date: "2026-02-28 10:48",
  },
  {
    id: "PAY-9811",
    orderId: "ORD-2026-002",
    userName: "Ana Belén Paredes",
    userEmail: "ana.paredes@constructora.ec",
    amount: 360.0,
    method: "card",
    status: "completed",
    date: "2026-02-27 15:21",
  },
  {
    id: "PAY-9810",
    orderId: "ORD-2026-003",
    userName: "Estudio Arquitectura Vértice",
    userEmail: "proyectos@vertice.ec",
    amount: 106.0,
    method: "card",
    status: "pending",
    date: "2026-02-28 11:30",
  },
];

export const INITIAL_USERS = [
  {
    id: "usr-1",
    name: "Antony Zumba (Super Admin)",
    email: "admin@ectyre.com",
    role: "ADMIN",
    status: "ACTIVE",
    ordersCount: 14,
    totalSpent: 2840.0,
    createdAt: "2026-01-01",
  },
  {
    id: "usr-2",
    name: "Carlos Mendoza",
    email: "carlos.mendoza@gmail.com",
    role: "CUSTOMER",
    status: "ACTIVE",
    ordersCount: 3,
    totalSpent: 590.25,
    createdAt: "2026-01-15",
  },
  {
    id: "usr-3",
    name: "Ana Belén Paredes",
    email: "ana.paredes@constructora.ec",
    role: "CUSTOMER",
    status: "ACTIVE",
    ordersCount: 6,
    totalSpent: 1840.5,
    createdAt: "2026-01-20",
  },
  {
    id: "usr-4",
    name: "Constructora Loja Sur",
    email: "compras@lojasur.ec",
    role: "CUSTOMER",
    status: "INACTIVE",
    ordersCount: 0,
    totalSpent: 0.0,
    createdAt: "2026-02-10",
  },
];

export const INITIAL_SETTINGS = {
  businessName: "ECTYRE S.A.S.",
  commercialName: "ECTYRE Materiales y Acabados",
  taxId: "1792837461001",
  dispatchEmail: "despachos@ectyre.com",
  whatsappNumber: "+593 98 765 4321",
  physicalAddress: "Av. Principal y Panamericana Sur Km 4.5, Quito, Ecuador",
  currency: "USD",
  timeZone: "America/Guayaquil (GMT-5)",
  stripePublishableKey: "pk_test_51Mz0...exampleKey",
};
